### ISSUE TITLE
Let Jasmine handle promises in tests

### ISSUE THREAD

**Issue by raphinesse** [apache/cordova#169]
Almost all asynchronous interfaces we provide or work with, make use of Promises. Jasmine has elegant [built-in support for handling promises](https://jasmine.github.io/tutorials/async#promises). Nonetheless, most asynchronous legacy tests don't make use of it. Instead, they are using makeshift and often buggy constructs using Jasmine's callback-style asynchronous tests (using the `done` parameter).

In many repos the transition to a simpler more robust Promise handling in tests has already been made. This issue should serve as a checklist of the remaining work in this area.

It's also often helpful to make this transition before removing Q (#7) in the given repo.

Of course, there are perfectly acceptable usages of `done`, most notably when working with callback-based async interfaces. But these are the vast minority in our tests.

## Task list
(only repos that feature or featured usage of `done`)

### Tools/libs
- [x] [cordova-cli](https://github.com/apache/cordova-cli/pull/315)
- [x] [cordova-lib](https://github.com/apache/cordova-lib/pull/619)
- [x] [cordova-create](https://github.com/apache/cordova-create/pull/13)
- [x] [cordova-fetch](https://github.com/apache/cordova-fetch/pull/16)
- [x] [cordova-common](https://github.com/apache/cordova-common/pull/79)
- [x] ~~cordova-js~~ (acceptable usage)
- [x] [cordova-serve](https://github.com/apache/cordova-serve/pull/20)

### Platforms
  - [x] [cordova-android](https://github.com/apache/cordova-android/pull/787)
  - [x] [cordova-browser](https://github.com/apache/cordova-browser/pull/85)
  - [x] [cordova-ios](https://github.com/apache/cordova-ios/pull/705)
  - [x] [cordova-windows](https://github.com/apache/cordova-windows/pull/366)

### Plugins
- [x] ~~cordova-plugin-battery-status~~ (acceptable usage)
- [x] ~~cordova-plugin-file~~ (acceptable usage)
- [x] ~~cordova-plugin-geolocation~~ (acceptable usage)
- [x] ~~cordova-plugin-inappbrowser~~ (acceptable usage)
- [x] ~~cordova-plugin-media~~ (acceptable usage)
- [x] [cordova-plugin-screen-orientation](https://github.com/apache/cordova-plugin-screen-orientation/pull/57)

**Comment by raphinesse** [comment]
For future reference. You can find all usage of Jasmine's `done` with the following ESLint config:
```yaml
rules:
    no-restricted-syntax:
        - error
        - selector: 'CallExpression[callee.name=it] > :function:nth-child(2) > :first-child'
          message: "Jasmine's done is not allowed"
```
