### ISSUE TITLE
[Plugins] Clean up plugin tests

### ISSUE THREAD

**Issue by janpio** [apache/cordova#28]
Make sure plugin tests:

- [ ] do not fail by default
	- [x] https://github.com/apache/cordova/issues/27 browser tests failing
    - [x] https://github.com/apache/cordova/issues/35 Android tests failing
    - [x] https://github.com/apache/cordova/issues/36 iOS tests failing
	- [ ] cordova-plugin-whitelist: no test config: https://github.com/apache/cordova-plugin-whitelist/issues/29
    - [x] cordova-plugin-file + Safari: https://github.com/apache/cordova-plugin-file/issues/257
    - [x] cordova-plugin-inappbrowser + Android 7: https://github.com/apache/cordova-plugin-inappbrowser/issues/307
- [x] do not fail on current `master`
	- [x] [cordova-plugin-battery-status](https://github.com/apache/cordova-plugin-battery-status)
	- [x] [cordova-plugin-camera](https://github.com/apache/cordova-plugin-camera)
	- [x] [cordova-plugin-device](https://github.com/apache/cordova-plugin-device)
	- [x] [cordova-plugin-dialogs](https://github.com/apache/cordova-plugin-dialogs)
	- ~~[cordova-plugin-file](https://github.com/apache/cordova-plugin-file)~~ see above
	- [x] [cordova-plugin-geolocation](https://github.com/apache/cordova-plugin-geolocation)
	- ~~[cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser)~~ see above
	- [x] [cordova-plugin-media](https://github.com/apache/cordova-plugin-media)
	- [x] [cordova-plugin-media-capture](https://github.com/apache/cordova-plugin-media-capture)
	- [x] [cordova-plugin-network-information](https://github.com/apache/cordova-plugin-network-information)
	- [x] [cordova-plugin-screen-orientation](https://github.com/apache/cordova-plugin-screen-orientation)
	- [x] [cordova-plugin-splashscreen](https://github.com/apache/cordova-plugin-splashscreen)
	- [x] [cordova-plugin-statusbar](https://github.com/apache/cordova-plugin-statusbar)
	- [x] [cordova-plugin-vibration](https://github.com/apache/cordova-plugin-vibration)
	- ~~[cordova-plugin-whitelist](https://github.com/apache/cordova-plugin-whitelist)~~ see above
	- [x] [cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine)

This issue will only be closed, when all `master` and new PRs only fail by _real_ test failures of broken functionality.

**Comment by janpio** [comment]
Link to `package.json`:

- [apache/cordova-plugin-battery-status](https://github.com/apache/cordova-plugin-battery-status/blob/master/package.json)
- [apache/cordova-plugin-camera](https://github.com/apache/cordova-plugin-camera/blob/master/package.json)
- [apache/cordova-plugin-device](https://github.com/apache/cordova-plugin-device/blob/master/package.json)
- [apache/cordova-plugin-dialogs](https://github.com/apache/cordova-plugin-dialogs/blob/master/package.json)
- [apache/cordova-plugin-file](https://github.com/apache/cordova-plugin-file/blob/master/package.json)
- [apache/cordova-plugin-geolocation](https://github.com/apache/cordova-plugin-geolocation/blob/master/package.json)
- [apache/cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/package.json)
- [apache/cordova-plugin-media](https://github.com/apache/cordova-plugin-media/blob/master/package.json)
- [apache/cordova-plugin-media-capture](https://github.com/apache/cordova-plugin-media-capture/blob/master/package.json)
- [apache/cordova-plugin-network-information](https://github.com/apache/cordova-plugin-network-information/blob/master/package.json)
- [apache/cordova-plugin-screen-orientation](https://github.com/apache/cordova-plugin-screen-orientation/blob/master/package.json)
- [apache/cordova-plugin-splashscreen](https://github.com/apache/cordova-plugin-splashscreen/blob/master/package.json)
- [apache/cordova-plugin-statusbar](https://github.com/apache/cordova-plugin-statusbar/blob/master/package.json)
- [apache/cordova-plugin-vibration](https://github.com/apache/cordova-plugin-vibration/blob/master/package.json)
- [apache/cordova-plugin-whitelist](https://github.com/apache/cordova-plugin-whitelist/blob/master/package.json)
- [apache/cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine/blob/master/package.json)

Link to `.travis.yml`:
- [apache/cordova-plugin-battery-status](https://github.com/apache/cordova-plugin-battery-status/blob/master/.travis.yml)
- [apache/cordova-plugin-camera](https://github.com/apache/cordova-plugin-camera/blob/master/.travis.yml)
- [apache/cordova-plugin-device](https://github.com/apache/cordova-plugin-device/blob/master/.travis.yml)
- [apache/cordova-plugin-dialogs](https://github.com/apache/cordova-plugin-dialogs/blob/master/.travis.yml)
- [apache/cordova-plugin-file](https://github.com/apache/cordova-plugin-file/blob/master/.travis.yml)
- [apache/cordova-plugin-geolocation](https://github.com/apache/cordova-plugin-geolocation/blob/master/.travis.yml)
- [apache/cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/.travis.yml)
- [apache/cordova-plugin-media](https://github.com/apache/cordova-plugin-media/blob/master/.travis.yml)
- [apache/cordova-plugin-media-capture](https://github.com/apache/cordova-plugin-media-capture/blob/master/.travis.yml)
- [apache/cordova-plugin-network-information](https://github.com/apache/cordova-plugin-network-information/blob/master/.travis.yml)
- [apache/cordova-plugin-screen-orientation](https://github.com/apache/cordova-plugin-screen-orientation/blob/master/.travis.yml)
- [apache/cordova-plugin-splashscreen](https://github.com/apache/cordova-plugin-splashscreen/blob/master/.travis.yml)
- [apache/cordova-plugin-statusbar](https://github.com/apache/cordova-plugin-statusbar/blob/master/.travis.yml)
- [apache/cordova-plugin-vibration](https://github.com/apache/cordova-plugin-vibration/blob/master/.travis.yml)
- [apache/cordova-plugin-whitelist](https://github.com/apache/cordova-plugin-whitelist/blob/master/.travis.yml)
- [apache/cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine/blob/master/.travis.yml)

Link to `.appveyor.yml`:
- [apache/cordova-plugin-battery-status](https://github.com/apache/cordova-plugin-battery-status/blob/master/.appveyor.yml)
- [apache/cordova-plugin-camera](https://github.com/apache/cordova-plugin-camera/blob/master/.appveyor.yml)
- [apache/cordova-plugin-device](https://github.com/apache/cordova-plugin-device/blob/master/.appveyor.yml)
- [apache/cordova-plugin-dialogs](https://github.com/apache/cordova-plugin-dialogs/blob/master/.appveyor.yml)
- [apache/cordova-plugin-file](https://github.com/apache/cordova-plugin-file/blob/master/.appveyor.yml)
- [apache/cordova-plugin-geolocation](https://github.com/apache/cordova-plugin-geolocation/blob/master/.appveyor.yml)
- [apache/cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/.appveyor.yml)
- [apache/cordova-plugin-media](https://github.com/apache/cordova-plugin-media/blob/master/.appveyor.yml)
- [apache/cordova-plugin-media-capture](https://github.com/apache/cordova-plugin-media-capture/blob/master/.appveyor.yml)
- [apache/cordova-plugin-network-information](https://github.com/apache/cordova-plugin-network-information/blob/master/.appveyor.yml)
- [apache/cordova-plugin-screen-orientation](https://github.com/apache/cordova-plugin-screen-orientation/blob/master/.appveyor.yml)
- [apache/cordova-plugin-splashscreen](https://github.com/apache/cordova-plugin-splashscreen/blob/master/.appveyor.yml)
- [apache/cordova-plugin-statusbar](https://github.com/apache/cordova-plugin-statusbar/blob/master/.appveyor.yml)
- [apache/cordova-plugin-vibration](https://github.com/apache/cordova-plugin-vibration/blob/master/.appveyor.yml)
- [apache/cordova-plugin-whitelist](https://github.com/apache/cordova-plugin-whitelist/blob/master/.appveyor.yml)
- [apache/cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine/blob/master/.appveyor.yml)
