### ISSUE TITLE
Add Node 10 & Drop Node 4 Support

### ISSUE THREAD

**Issue by erisu** [apache/cordova#5]
## Goal
- Drop Node 4 Support
- Add Node 10 Support

##### Task List
- [x] cordova-common
- [x] cordova-lib
- [x] cordova-fetch
- [x] cordova-create
- [x] cordova-cli
- [x] cordova-serve (https://github.com/apache/cordova-serve/pull/12)
- [x] cordova-plugman
- [x] cordova-js (https://github.com/apache/cordova-js/pull/168)
- [x] cordova-android
- [x] cordova-browser (https://github.com/apache/cordova-browser/pull/58)
- [x] cordova-ios
- [x] cordova-osx (https://github.com/apache/cordova-osx/pull/53)
- [x] cordova-window

**Comment by erisu** [comment]
## Review
**Target:** cordova-common
**Status:** Complete

https://github.com/apache/cordova-common/commit/d473b190960ae3401ede0993994220c89d262bc0
- [x] package.json

https://github.com/apache/cordova-common/commit/adf90039c1a42bf1664dba91dbadaac504b82f5a
- [x] AppVeyor
- [x] Travis CI

**Comment by erisu** [comment]
## Review
**Target:** cordova-lib
**Status:** Complete

https://github.com/apache/cordova-lib/commit/61395d2946a743a0a5ad5bf273a57701af15a145
- [x] package.json
- [x] AppVeyor
- [x] Travis CI

**Comment by erisu** [comment]
## Review
**Target:** cordova-fetch
**Status:** Complete

https://github.com/apache/cordova-fetch/commit/b0040a463b0f3f22fe03f17f79686d2b820b7e37
- [x] package.json
- [x] AppVeyor
- [x] Travis CI

**Comment by erisu** [comment]
## Review
**Target:** cordova-create
**Status:** Complete

https://github.com/apache/cordova-create/commit/7e40c4558ad8ff018a6f8c272a2cbd5e7715691b
- [x] package.json
- [x] AppVeyor
- [x] Travis CI

**Comment by erisu** [comment]
## Review
**Target:** cordova-cli
**Status:** Complete

https://github.com/apache/cordova-cli/commit/f567c26f2eed45af2d5aa5ef3d825f18297d4cd6
- [x] package.json
- [x] AppVeyor
- [x] Travis CI

**Comment by erisu** [comment]
## Review
**Target:** cordova-serve
**Status:** Not started

- [ ] package.json
- [ ] AppVeyor
- [ ] Travis CI

**Comment by erisu** [comment]
## cordova-plugman Review
**Status:** Completed

https://github.com/apache/cordova-plugman/commit/e310ac51f17df8a45e8c1030f0c65027a943065b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
- [x] package.json

## Future Tasks
* Add Travis CI
* Add AppVeyor

**Comment by erisu** [comment]
## cordova-js Review
**Status:** Not Started

- [ ] package.json
- [ ] Travis CI
- [ ] AppVeyor
