### ISSUE TITLE
Remove committed `node_modules` from platforms

### ISSUE THREAD

**Issue by raphinesse** [apache/cordova#6]
We don't need them anymore since CLI installs all dependencies properly now. Not having to bundle dependencies vastly simplifies adding a new dependency if you need it for a feature.

Tooling and core plugins are *not* affected.

##### Task List
- [x] [cordova-android](https://github.com/apache/cordova-android/pull/493)
- [x] [cordova-browser](https://github.com/apache/cordova-browser/pull/59)
- [x] [cordova-ios](https://github.com/apache/cordova-ios/pull/388)
- [x] [cordova-osx](https://github.com/apache/cordova-osx/pull/54)
- [x] [cordova-windows](https://github.com/apache/cordova-windows/pull/293)
- [x] [cordova-coho release docs](https://github.com/apache/cordova-coho/pull/198)

**Comment by janpio** [comment]
(Added "Cordova coho Release Process documentation" as task)

**Comment by erisu** [comment]
For https://github.com/apache/cordova-ios/pull/388, conflicts needs to be resolved and should be OK for merging since I last reviewed it. Would like a second opinion.

**Comment by erisu** [comment]
It seems https://github.com/apache/cordova-osx/pull/49, covers removing the node_modules and many other smaller tasks. Could the node_module and bundled packages removal be cherry-picked?
