### ISSUE TITLE
Drop dependency on Q, use native promises

### ISSUE THREAD

**Issue by raphinesse** [apache/cordova#7]
We have to do this top down in our dependency graph. That way, we always can release each package without risking to break any of its consumers that rely on Q instances being returned. The order in the following task list is a topological ordering of the below dependency graph. So if we do everything in this order, each package will be processed before any of its dependencies.

There are no plugins that depend on Q.

## Task list

- [x] [cordova-plugman](https://github.com/apache/cordova-plugman/pull/94)
- [x] [cordova-cli](https://github.com/apache/cordova-cli/pull/289)
- [x] [cordova-lib](https://github.com/apache/cordova-lib/pull/710)
- [x] [cordova-create](https://github.com/apache/cordova-create/pull/33)
- [x] [cordova-fetch](https://github.com/apache/cordova-fetch/pull/49)
- **Platforms**
  - [x] [cordova-android](https://github.com/apache/cordova-android/pull/833)
  - [x] [cordova-browser](https://github.com/apache/cordova-browser/pull/78/files)
  - [x] [cordova-ios](https://github.com/apache/cordova-ios/pull/860)
  - [x] [cordova-osx](https://github.com/apache/cordova-osx/pull/115)
  - [x] [cordova-windows](https://github.com/apache/cordova-windows/pull/395)
- [x] [cordova-common](https://github.com/apache/cordova-common/pull/99)
- [x] cordova-coho

## Cordova Dependency Graph
*Only packages with outstanding work in this issue*
![Cordova dependency graph](https://graphviz2.glitch.me/graphviz?graph=digraph+G+%7B%0Asubgraph+cluster_platforms+%7B%0Alabel+%3D+%22platforms%22%3B%0A%22cordova-android%22%3B%0A%22cordova-windows%22%3B%0A%22cordova-ios%22%3B%0A%22cordova-osx%22%3B%0A%7D%0A%22cordova-android%22+-%3E+%22cordova-common%22%3B%0A%22cordova-android%22+-%3E+%22q%22%3B%0A%22cordova-ios%22+-%3E+%22cordova-common%22%3B%0A%22cordova-ios%22+-%3E+%22q%22%3B%0A%22cordova-windows%22+-%3E+%22cordova-common%22%3B%0A%22cordova-windows%22+-%3E+%22q%22%3B%0A%22cordova-osx%22+-%3E+%22cordova-common%22%3B%0A%22cordova-osx%22+-%3E+%22q%22%3B%0A%22cordova-coho%22+-%3E+%22q%22%3B%0A%22cordova-common%22+-%3E+%22q%22%3B%0A%7D&layout=dot&format=svg&mode=download)

**Comment by raphinesse** [comment]
I've added a full dependency graph to make it easier to determine the correct order of doing this.

**Comment by raphinesse** [comment]
To bad nobody wrote an automated code transformation based on [jscodeshift](https://github.com/facebook/jscodeshift) for migrating from Q to native Promises.

**Comment by brodybits** [comment]
Another thing is that I think we should get rid of `superspawn` as discussed in #16, rather than fixing `superspawn` to drop use of `q`. The rationale is that `superspawn` seems to return a non-standard Promise-like object that can also notify the listener of `stdout` and `stderr` data. I think it would be better to cleanly factor `superspawn` out of the Cordova packages, in a major release.

While it would be ideal to do this in the next major release, it would likely block some other desired changes such as dropping support for Node.js 6 and eventually Node.js 8.

**Comment by erisu** [comment]
@brodybits Can you elaborate on this?
> it would likely block some other desired changes such as dropping support for Node.js 6 and eventually Node.js 8.

To drop Node.js 6 and 8 in the next major as planned, we only remove it from the CI testing configurations and bump the node engine in `package.json. There shouldn't be much effort to this.

**Comment by brodybits** [comment]
@erisu I only wanted to give examples of some major changes that I *know* are wanted in an upcoming releases, and that I think should not be blocked by removing `superspawn` (#16). I suspect that #16 could be a major effort to implement and test on all of the various Cordova packages.

I hope this is clear now. Please feel free to ask if it is still not clear.

**Comment by erisu** [comment]
Thank you @brodybits that cleared up my confusion.

**Comment by raphinesse** [comment]
I wrote an ESLint config that should highlight all instances of Q-API usage:
```js
const qInstanceMethodsConfig = `
    allResolved allSettled del delay denodeify dispatch done fail fapply fbind
    fcall fin invoke isFulfilled isPending isRejected mapply mcall nbind
    nfapply nfbind nfcall ninvoke nmapply nmcall nodeify npost nsend passByCopy
    post progress spread tap thenReject thenResolve timeout
`.trim().split(/\s+/).map(property => ({ property }));

const restrictedSyntaxConfig = [
    {
        selector: `
            CallExpression[arguments.length=1][arguments.0.value!=/^(,? ?|\\n)$/]
                > MemberExpression[property.name="join"][object.name!="path"][callee.object.type!="ArrayExpression"]
        `.replace(/\n/g, ''),
        message: 'possible usage of `Q.prototype.join`',
    },
    {
        selector: 'CallExpression[arguments.length=1] > MemberExpression[property.name="get"]',
        message: 'possible usage of `Q.prototype.get`',
    },
    {
        selector: 'CallExpression[arguments.length=2] > MemberExpression[property.name="set"]',
        message: 'possible usage of `Q.prototype.set`',
    },
    {
        selector: 'CallExpression > MemberExpression[property.name="any"][object.name!="jasmine"]',
        message: 'possible usage of `Q.prototype.any`',
    },
    {
        selector: 'CallExpression > MemberExpression[property.name="keys"][object.name!="Object"]',
        message: 'possible usage of `Q.prototype.keys`',
    },
    {
        selector: 'CallExpression[callee.property.name="send"]',
        message: 'possible usage of `Q.prototype.send`',
    },
]

module.exports = {
    rules: {
        'no-restricted-modules': ['error', 'q'],
        'no-restricted-properties': [
            'error', { object: 'Q' }, { object: 'q' }, ...qInstanceMethodsConfig
        ],
        'no-restricted-syntax': ['warn', ...restrictedSyntaxConfig],
    }
};
```

**Comment by erisu** [comment]
Closing as resolved
