### ISSUE TITLE
Remove `browserify` support

### ISSUE THREAD

**Issue by raphinesse** [apache/cordova#8]
## Tasks
- [x] [cordova-cli](https://github.com/apache/cordova-cli/pull/321)
- [x] [cordova-lib](https://github.com/apache/cordova-lib/pull/682)
- [x] [cordova-plugman](https://github.com/apache/cordova-plugman/pull/95)
- [x] [cordova-coho](https://github.com/apache/cordova-coho/pull/197)
- [x] [cordova-js](https://github.com/apache/cordova-js/pull/162)
- [x] Check for any other occurrences

## Future work
There's two places in platforms that mention browserify which probably could be simplified after the removal:

https://github.com/apache/cordova-android/blob/46a036ef265951d5371936b37d7296fa47fb28ce/bin/lib/create.js#L71-L73

https://github.com/apache/cordova-osx/blob/7faf6aaa426136ea4224f52db44cc7aab464498a/bin/templates/scripts/cordova/Api.js#L72-L75

**Comment by janpio** [comment]
Found one more: https://github.com/apache/cordova-paramedic#--browserify-optional

**Comment by erisu** [comment]
Is this task completed? can we move it to the Done column on the project board?

https://github.com/orgs/apache/projects/2

**Comment by raphinesse** [comment]
@erisu I don't know if anyone removed the leftovers from paramedic. If not, we should create an issue for it.

Since paramedic is meta-tooling and not part of our release plan, I think we can mark this as done anyway.

**Comment by erisu** [comment]
Closing as suggested.
Ticket has been created in paramedic to keep track of this request: https://github.com/apache/cordova-paramedic/issues/85
